### ISSUE TITLE
Pas de release

### ISSUE THREAD

**Issue by Teyk0o** [Azuriom/AzAuth#2]
Bonsoir, il n'y as pas de release de publier, on est censer faire comment ?

**Comment by ArnaudLier** [comment]
https://azuriom.com/azlink

**Comment by SkyWarZzeur** [comment]
> https://azuriom.com/azlink

c'est pas azlink mais azauth

Pour le moment tu peux utiliser ce lien: https://azuriom.com/storage/azauth-1.0-SNAPSHOT.jar
On fera une release dans la soirée!

**Comment by MaximeMichaud** [comment]
> Bonsoir, il n'y as pas de release de publier, on est censer faire comment ?

Je peux aussi faire comme pour AzLink où que chaque commit crée un build sur GitHub.
![image](https://user-images.githubusercontent.com/14856114/76689134-55e48580-6609-11ea-8a0a-f8377843cfd6.png)
