### ISSUE TITLE
IllegalStateException gets set off while trying to authenticate a user.

### ISSUE THREAD

**Issue by Kuba663** [Azuriom/AzAuth#4]
While trying to execute AzAuthenticator.authenticate an exception sets off.
The code:
```
package gq.speedcraft.www.launcher;

import java.io.File;
import java.io.IOException;
import java.util.Collections;

import com.azuriom.azauth.AuthenticationException;
import com.azuriom.azauth.AzAuthenticator;

import fr.theshark34.openlauncherlib.LaunchException;
import fr.theshark34.openlauncherlib.external.ExternalLaunchProfile;
import fr.theshark34.openlauncherlib.external.ExternalLauncher;
import fr.theshark34.openlauncherlib.minecraft.AuthInfos;
import fr.theshark34.openlauncherlib.minecraft.GameFolder;
import fr.theshark34.openlauncherlib.minecraft.GameInfos;
import fr.theshark34.openlauncherlib.minecraft.GameTweak;
import fr.theshark34.openlauncherlib.minecraft.GameType;
import fr.theshark34.openlauncherlib.minecraft.GameVersion;
import fr.theshark34.openlauncherlib.minecraft.MinecraftLauncher;
import fr.theshark34.openlauncherlib.util.Saver;

public class Launcher {
	private GameInfos infos;
	private GameVersion version;
	private AuthInfos authInfos;
	private File DIR;
	public Launcher(String version, GameType type,GameTweak... tweaks) {
		this.version = new GameVersion("1.12", GameType.V1_8_HIGHER);
		this.infos = new GameInfos("speedcraft.pl",this.version, tweaks);
		this.DIR = this.infos.getGameDir();
	}

	public void auth(String username, String password) throws AuthenticationException, IOException
	{
		AzAuthenticator testAuth = new AzAuthenticator("https://speedcraft.gq");
		authInfos = testAuth.authenticate(username, password, AuthInfos.class);
	}
	public void launch() throws  LaunchException
	{
		ExternalLaunchProfile profile = MinecraftLauncher.createExternalProfile(infos, GameFolder.BASIC, authInfos);
		ExternalLauncher launcher = new ExternalLauncher(profile);
		Process process = launcher.launch();
		try {
			process.waitFor();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
```
The Exception:

> com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:200)
	at com.google.gson.Gson.fromJson(Gson.java:810)
	at com.google.gson.Gson.fromJson(Gson.java:748)
	at com.azuriom.azauth.AzAuthenticator.post(AzAuthenticator.java:173)
	at com.azuriom.azauth.AzAuthenticator.authenticate(AzAuthenticator.java:94)
	at gq.speedcraft.www.launcher.Launcher.auth(Launcher.java:43)
	at gq.speedcraft.www.launcher.LauncherThread.run(LauncherThread.java:23)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:387)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:189)
	... 6 more
_note: I am not the owner of the site "https://speedcraft.gq". I am just a dev who has been hired to program a launcher for a server_

**Comment by MrMicky-FR** [comment]
Hi, it’s most likely because the website isn’t return data in JSON format. This can come from a firewall blocking the request or something like that.
