### ISSUE TITLE
Add 2FA support on AzAuth

### ISSUE THREAD

**Issue by OdysseyusProject** [Azuriom/AzAuth#5]
It would be nice if we could use the A2F for our launcher or make it open a web page where we can connect (so adding the A2F)

**Comment by antonin-lst** [comment]
désolée j'avais pas vu le post, une date de mise à jour ?

**Comment by MrMicky-FR** [comment]
Ca sera d’ici moins d’un mois normalement

**Comment by antonin-lst** [comment]
Merci mais j’ai fork la lib et ajouter la possibilité de passer le code de la 2fa au body json, merci d’avoir déjà fait la logique de la 2fa dans la route d’auth api

**Comment by MrMicky-FR** [comment]
Un apercu de la version est disponible dans la pull request #7
